[versions]
plugin-android = "9.2.1"
plugin-publish-maven = "0.37.0"

android-compileSdk = "37"
android-targetSdk = "37"
android-minSdk = "21"

kotlin = "2.4.0"
coroutines = "1.11.0"
serialization = "1.11.0"
browser = "0.5.0"
jackson = "2.22.0"
kotlinpoet = "2.3.0"

junit = "4.13.2"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-publish-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-publish-maven" }
plugin-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-jb" }
plugin-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "browser" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

test-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-junit = { module = "junit:junit", version.ref = "junit" }