[versions]
plugin-android = "9.2.1"
plugin-publish-maven = "0.37.0"

android-compileSdk = "37"
android-targetSdk = "37"
android-minSdk = "21"

kotlin = "2.4.0"
serialization = "1.11.0"
xmlutil = "1.0.0-rc3"
kotlinpoet = "2.3.0"

junit = "4.13.2"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-publish-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-publish-maven" }
plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
xmlutil = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

test-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-junit = { module = "junit:junit", version.ref = "junit" }